### ISSUE TITLE
Can't Access Graphite-web from the host

### ISSUE THREAD

**Issue by rrpolanco** [nickstenning/docker-graphite#10]
Hi,

I'm running the latest Docker native client(Version 1.12.0-rc3-beta18)  for MacOS. 
Did `docker run -d nickstenning/graphite` and the container started successfully.

However, I can't seem to reach the Graphite-Web interface from `http://127.0.0.1` nor from the container's IP addr `http://172.17.0.2`. Maybe I'm missing something simple. Any help is appreciated. 

Thanks.

**Comment by monokal** [comment]
You need to specify the host ports too. This works for me:
```
docker run -p 8080:8080 -p 2003:2003 -p 2004:2004 -p 7002:7002 -d schaubl/graphite
```

**Comment by nickstenning** [comment]
I think @monokal is right that you need to make sure you've exposed the relevant ports with Docker's `-p` option. Closing.
