### ISSUE TITLE
admin/admin credentials do not work.

### ISSUE THREAD

**Issue by monokal** [nickstenning/docker-graphite#11]
admin/admin credentials do not work when trying to log in to the Graphite web interface.

**Comment by Haegin** [comment]
They work fine for me, though I'm running graphite on localhost:5002 and after logging in I get redirected to just localhost (so port 80) which unsurprisingly doesn't work. If I manually navigate back to localhost:5002 I'm logged in correctly. Is this the same issue you're seeing @monokal?

**Comment by nickstenning** [comment]
I think @Haegin is probably right about the issue here, and the change I just merged in #13 probably addresses that. Closing.
