### ISSUE TITLE
Error Could not load dashboards/default.json. Please make sure it exists

### ISSUE THREAD

**Issue by cmadsen** [nickstenning/docker-graphite#4]
Doing `docker run -d nickstenning/graphite` and accessing http://localhost:80  gives:

`Error Could not load dashboards/default.json. Please make sure it exists`

Looks like screenshot here https://github.com/grafana/grafana/issues/794

**Comment by nickstenning** [comment]
Not sure what this is about, because this image doesn't contain grafana. Either way, there are no errors visible when loading the default web page served by this image.
