### ISSUE TITLE
docker build github.com/nickstenning/docker-graphite results in a broken image

### ISSUE THREAD

**Issue by ctwise** [nickstenning/docker-graphite#6]
When I build an image from the repository using:

    docker build github.com/nickstenning/docker-graphite

I get an image that mostly works but appears to be expecting a timezone function which I believe is in Django 1.4.

![width 586 height 308 _salt 1429561319 027 2015-04-20 16-22-30](https://cloud.githubusercontent.com/assets/5510/7239958/ae61b848-e77b-11e4-8099-cde7358162fe.png)

**Comment by ctwise** [comment]
Looks like the current version of Graphite requires Django 1.4 which isn't in Ubuntu 12.04. You can force whisper, carbon and graphite to the version of 0.9.12 which is the last version which runs under Django 1.3.

**Comment by nickstenning** [comment]
I've updated the image to build 0.9.15, and it should work ok now. Thanks for reporting this, and sorry it took so long to fix it!
